import React from 'react';
import { X, Shield, Lock, FileText } from 'lucide-react';

interface LegalModalProps {
  type: 'privacy' | 'terms' | 'security' | null;
  onClose: () => void;
}

export const LegalModal: React.FC<LegalModalProps> = ({ type, onClose }) => {
  if (!type) return null;

  const contentMap = {
    privacy: {
      icon: Lock,
      title: 'Avichas Privacy Policy',
      kicker: 'DATA SOVEREIGNTY & PRIVACY',
      text: [
        'At Avichas Metrics, privacy is an architectural guarantee rather than an afterthought. We implement single-tenant logical isolation for customer data repositories.',
        'Zero-Training Commitment: Your organizational telemetry, OKRs, and performance metrics are strictly sequestered and never used to train generalized foundation models or shared across commercial tenants.',
        'Data Retention & Deletion: Customers retain 100% data ownership. Upon enterprise termination or request, data is permanently scrubbed using cryptographically verifiable DoD 5220.22-M sanitization protocols.',
      ],
    },
    terms: {
      icon: FileText,
      title: 'Enterprise Terms of Service',
      kicker: 'GOVERNANCE & SERVICE AGREEMENTS',
      text: [
        'Avichas Metrics provides enterprise operational execution intelligence under strict service level agreements ensuring 99.95% continuous telemetry uptime.',
        'Role-Based Authorization: Enterprise administrators maintain complete authority over granular permissions, metric verification workflows, and audit sign-off chains.',
        'Deterministic Computing: Insights and risk indicators generated by Avichas are bound by verifiable business logic and verifiable provenance logs.',
      ],
    },
    security: {
      icon: Shield,
      title: 'Security & Compliance Architecture',
      kicker: 'CRYPTOGRAPHIC TRUST & COMPLIANCE',
      text: [
        'Certified Compliance: Avichas undergoes continuous third-party attestation against SOC 2 Type II, ISO/IEC 27001, and HIPAA Security Rule criteria.',
        'Encryption: End-to-end envelope encryption using AES-256 for all stored metrics and TLS 1.3 with forward secrecy for all operational telemetric ingest streams.',
        'Customer-Managed Keys (CMEK): Integrate your own AWS KMS, Google Cloud KMS, or Azure Key Vault for full sovereign control over data decryptions.',
      ],
    },
  };

  const item = contentMap[type];
  const Icon = item.icon;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md animate-in fade-in duration-200">
      <div className="relative w-full max-w-xl bg-[#0C1524] border border-white/20 rounded-2xl shadow-2xl overflow-hidden flex flex-col max-h-[85vh]">
        <div className="flex items-center justify-between px-6 py-4 bg-[#09101C] border-b border-white/10">
          <div className="flex items-center gap-2.5">
            <Icon className="w-5 h-5 text-[#C9975B]" />
            <h3 className="text-base font-bold text-white tracking-tight">
              {item.title}
            </h3>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 text-slate-400 hover:text-white rounded-lg hover:bg-white/10 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="p-6 sm:p-8 overflow-y-auto flex flex-col gap-4">
          <span className="text-[11px] font-semibold tracking-[0.2em] text-[#C9975B] uppercase font-mono">
            {item.kicker}
          </span>
          {item.text.map((paragraph, idx) => (
            <p key={idx} className="text-xs sm:text-sm text-slate-300 leading-relaxed">
              {paragraph}
            </p>
          ))}
          <div className="pt-4 border-t border-white/10 flex justify-end">
            <button
              onClick={onClose}
              className="px-5 py-2 rounded-lg bg-white/10 hover:bg-white/20 text-white text-xs font-medium transition-colors"
            >
              Acknowledge & Close
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
